pipeline {

    agent any

    stages {

        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                sh 'java -jar target/my-app-1.0-SNAPSHOT.jar > index.html'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    app = docker.build("chrisneal11/devops_capstone")
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub_login') {
                        app.push("${env.BUILD_NUMBER}")
                        app.push("latest")
                    }
                }
            }
        }        
      stage('Deploy To Production') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'webserver_login', usernameVariable: 'USERNAME', passwordVariable: 'USERPASS')]) {
                    script {
                        sh "ssh -i "/home/ubuntu/.ssh/aws-lab.pem" -o StrictHostKeyChecking=no ubuntu@172.31.18.102 \"docker pull chrisneal11/devops_capstone:latest\""
                        try {
                            sh "ssh -i "/home/ubuntu/.ssh/aws-lab.pem" -o StrictHostKeyChecking=no ubuntu@172.31.18.102 \"docker stop devops_capstone\""
                            sh "ssh -i "/home/ubuntu/.ssh/aws-lab.pem" -o StrictHostKeyChecking=no ubuntu@172.31.18.102 \"docker rm devops_capstone\""
                        } catch (err) {
                            echo: 'caught error: $err'
                        }
                        sh "ssh -i "/home/ubuntu/.ssh/aws-lab.pem" -o StrictHostKeyChecking=no ubuntu@172.31.18.102 \"docker run --restart always --name devops_capstone -p 8080:80 -d chrisneal11/devops_capstone:${env.BUILD_NUMBER}\""
                    }
                }
            }
        }
    }   
}
//  Valid IPs are 1721.31.18.102   Is MODE2 INTERNAL
//  Valid IPs are 1721.31.23.111   Is PROD1 INTERNAL
//
//
//      stage('Deploy To Production') {
//            steps {
//                withCredentials([usernamePassword(credentialsId: 'webserver_login', usernameVariable: 'USERNAME', passwordVariable: 'USERPASS')]) {
//                    script {
//                        sh "sshpass -p '$USERPASS' -v ssh -o StrictHostKeyChecking=no $USERNAME@$production_server_ip \"docker pull chrisneal11/devops_capstone:${env.BUILD_NUMBER}\""
//                        try {
//                            sh "sshpass -p '$USERPASS' -v ssh -o StrictHostKeyChecking=no $USERNAME@$produciton_server_ip \"docker stop devops_capstone\""
//                            sh "sshpass -p '$USERPASS' -v ssh -o StrictHostKeyChecking=no $USERNAME@$production_server_ip \"docker rm devops_capstone\""
//                        } catch (err) {
//                            echo: 'caught error: $err'
//                        }
//                        sh "sshpass -p '$USERPASS' -v ssh -o StrictHostKeyChecking=no $USERNAME@$production_server_ip \"docker run --restart always --name devops_capstone -p 8080:80 -d chrisneal11/devops_capstone:${env.BUILD_NUMBER}\""
//                    }
//                }
//            }
//        }

